import { useEffect, useState } from "react";

import {
  Activity,
  BarChart3,
  BookOpen,
  BrainCircuit,
  Database,
  History,
  LayoutDashboard,
  Menu,
  PackageSearch,
  ShieldAlert,
  SlidersHorizontal,
  Truck,
  X,
} from "lucide-react";

import {
  checkHealth,
  getDashboard,
  getHistorySummary,
} from "./services/api";

import Prediction from "./pages/Prediction";
import Analytics from "./pages/Analytics";
import BatchAnalysis from "./pages/BatchAnalysis";
import ShipmentExplorer from "./pages/ShipmentExplorer";
import ModelIntelligence from "./pages/ModelIntelligence";
import WhatIf from "./pages/WhatIf";
import PredictionHistory from "./pages/PredictionHistory";
import Guide from "./pages/Guide";
import InfoBanner from "./components/InfoBanner";


function Dashboard({ dashboard }) {

  const [historySummary, setHistorySummary] = useState(null);

  useEffect(() => {
    const loadHistory = async () => {
      try {
        const historyData = await getHistorySummary();
        if (historyData.success) {
          setHistorySummary(historyData);
        }
      } catch (error) {
        console.error("History load error:", error);
      }
    };
    loadHistory();
  }, []);

  if (!dashboard) {
    return (
      <div className="loading-screen">
        <Activity className="spin" size={28} />
        <span>Loading intelligence data...</span>
      </div>
    );
  }


  const summary = dashboard.summary;


  return (
    <>

      <div className="page-header">

        <div>

          <div className="eyebrow">
            COMMAND CENTER
          </div>

          <h1>
            Supply Chain Risk Intelligence
          </h1>

          <p>
            Monitor, analyze and predict shipment
            disruption risk using machine learning.
          </p>

        </div>

        <div className="header-status">

          <Activity size={18} />

          <span>
            AI Engine Active
          </span>

        </div>

      </div>


      <InfoBanner>
        <strong>
          New here?
        </strong>{" "}
        This is the overview of the system. Use{" "}
        <strong>
          How It Works
        </strong>{" "}
        in the sidebar for a full walkthrough of the
        platform, the models and every available page.
      </InfoBanner>


      {/* KPI CARDS */}

      <div className="metrics-grid">

        <div className="metric-card">

          <div className="metric-icon blue">
            <Truck size={20} />
          </div>

          <div>

            <div className="metric-label">
              ORDERS ANALYZED
            </div>

            <div className="metric-value">
              {summary.total_orders.toLocaleString()}
            </div>

            <div className="metric-change">
              Historical dataset
            </div>

          </div>

        </div>


        <div className="metric-card">

          <div className="metric-icon red">
            <ShieldAlert size={20} />
          </div>

          <div>

            <div className="metric-label">
              RISK CASES
            </div>

            <div className="metric-value">
              {summary.risk_cases.toLocaleString()}
            </div>

            <div className="metric-change">
              Historical risk records
            </div>

          </div>

        </div>


        <div className="metric-card">

          <div className="metric-icon amber">
            <Activity size={20} />
          </div>

          <div>

            <div className="metric-label">
              RISK RATE
            </div>

            <div className="metric-value">
              {summary.risk_rate}%
            </div>

            <div className="metric-change">
              Historical dataset
            </div>

          </div>

        </div>


        <div className="metric-card">

          <div className="metric-icon green">
            <BrainCircuit size={20} />
          </div>

          <div>

            <div className="metric-label">
              MODEL ROC-AUC
            </div>

            <div className="metric-value">
              {summary.model_roc_auc}%
            </div>

            <div className="metric-change">
              Verified test result
            </div>

          </div>

        </div>

      </div>


      {/* LIVE MONITOR */}

      {historySummary && (
        <div className="live-monitor-section">

          <div className="section-header">

            <div>
              <div className="eyebrow">
                LIVE DECISION MONITOR
              </div>

              <h2>
                Prediction Activity
              </h2>

              <p>
                Risk assessments generated by SupplyChainIQ
              </p>
            </div>

            <div className="live-indicator">
              <span></span>
              Live
            </div>

          </div>


          <div className="monitor-grid">

            <div className="monitor-card">

              <span>Total Predictions</span>

              <strong>
                {historySummary.total_predictions}
              </strong>

            </div>


            <div className="monitor-card high">

              <span>High Risk</span>

              <strong>
                {historySummary.high_risk}
              </strong>

            </div>


            <div className="monitor-card medium">

              <span>Medium Risk</span>

              <strong>
                {historySummary.medium_risk}
              </strong>

            </div>


            <div className="monitor-card low">

              <span>Low Risk</span>

              <strong>
                {historySummary.low_risk}
              </strong>

            </div>

          </div>


          <div className="monitor-bottom">

            <div>

              <span>Models Used</span>

              <div className="model-usage">

                {Object.entries(
                  historySummary.models || {}
                ).map(([model, count]) => (

                  <div
                    className="model-usage-row"
                    key={model}
                  >

                    <span>{model}</span>

                    <strong>{count}</strong>

                  </div>

                ))}

              </div>

            </div>


            <div className="latest-prediction">

              <span>Latest Assessment</span>

              {historySummary.latest ? (

                <>
                  <strong>
                    {historySummary.latest.risk_level}
                  </strong>

                  <small>
                    {historySummary.latest.model}
                  </small>

                  <small>
                    {new Date(
                      historySummary.latest.created_at
                    ).toLocaleString()}
                  </small>
                </>

              ) : (

                <small>
                  No predictions recorded yet.
                </small>

              )}

            </div>

          </div>

        </div>
      )}


      {/* ANALYTICS */}

      <div className="dashboard-grid">

        <div className="panel large">

          <div className="panel-header">

            <div>

              <h2>
                Risk Distribution
              </h2>

              <p>
                Historical shipment outcomes
              </p>

            </div>

            <div className="panel-badge">
              DATASET
            </div>

          </div>


          <div className="risk-overview">

            <div className="risk-circle">

              <div className="risk-circle-inner">

                <strong>
                  {summary.risk_rate}%
                </strong>

                <span>
                  Risk Rate
                </span>

              </div>

            </div>


            <div className="risk-summary">

              <div className="risk-row">

                <span>
                  Risk Cases
                </span>

                <strong>
                  {summary.risk_cases.toLocaleString()}
                </strong>

              </div>


              <div className="risk-row">

                <span>
                  No Risk
                </span>

                <strong>
                  {summary.no_risk_cases.toLocaleString()}
                </strong>

              </div>


              <div className="risk-row">

                <span>
                  Total Orders
                </span>

                <strong>
                  {summary.total_orders.toLocaleString()}
                </strong>

              </div>

            </div>

          </div>

        </div>


        {/* MODEL */}

        <div className="panel">

          <div className="panel-header">

            <div>

              <h2>
                AI Engine
              </h2>

              <p>
                Prediction system
              </p>

            </div>

            <div className="online-badge">
              ONLINE
            </div>

          </div>


          <div className="engine-info">

            <div className="engine-item">

              <span>
                Algorithm
              </span>

              <strong>
                CatBoost
              </strong>

            </div>


            <div className="engine-item">

              <span>
                Features
              </span>

              <strong>
                40
              </strong>

            </div>


            <div className="engine-item">

              <span>
                Accuracy
              </span>

              <strong>
                {summary.model_accuracy}%
              </strong>

            </div>


            <div className="engine-item">

              <span>
                ROC-AUC
              </span>

              <strong>
                {summary.model_roc_auc}%
              </strong>

            </div>

          </div>

        </div>

      </div>


      {/* SHIPPING ANALYSIS */}

      <div className="panel">

        <div className="panel-header">

          <div>

            <h2>
              Risk by Shipping Mode
            </h2>

            <p>
              Historical late-delivery risk by transportation mode
            </p>

          </div>

        </div>


        <div className="analytics-list">

          {dashboard.shipping_mode.map(
            (item) => (

              <div
                className="analytics-row"
                key={item["Shipping Mode"]}
              >

                <div className="analytics-label">

                  <Truck size={16} />

                  <span>
                    {item["Shipping Mode"]}
                  </span>

                </div>


                <div className="analytics-bar-container">

                  <div
                    className="analytics-bar"
                    style={{
                      width: `${item.risk_percentage}%`,
                    }}
                  />

                </div>


                <strong className="analytics-value">

                  {item.risk_percentage.toFixed(2)}%

                </strong>

              </div>

            )
          )}

        </div>

      </div>


      {/* CAPABILITIES */}

      <div className="panel">

        <div className="panel-header">

          <div>

            <h2>
              Platform Capabilities
            </h2>

            <p>
              SupplyChainIQ intelligence modules
            </p>

          </div>

        </div>


        <div className="capability-grid">

          <div className="capability">

            <ShieldAlert size={22} />

            <strong>
              Risk Prediction
            </strong>

            <span>
              Predict shipment late-delivery risk
              using machine learning.
            </span>

          </div>


          <div className="capability">

            <BarChart3 size={22} />

            <strong>
              Risk Analytics
            </strong>

            <span>
              Discover patterns across markets,
              regions and shipping modes.
            </span>

          </div>


          <div className="capability">

            <PackageSearch size={22} />

            <strong>
              Batch Analysis
            </strong>

            <span>
              Analyze large shipment datasets
              in a single operation.
            </span>

          </div>


          <div className="capability">

            <BrainCircuit size={22} />

            <strong>
              AI Intelligence
            </strong>

            <span>
              Understand important factors
              contributing to predicted risk.
            </span>

          </div>

        </div>

      </div>

    </>
  );
}


function App() {

  const [sidebarOpen, setSidebarOpen] =
    useState(true);

  const [apiStatus, setApiStatus] =
    useState("Checking...");

  const [page, setPage] =
    useState("dashboard");

  const [dashboard, setDashboard] =
    useState(null);

  const [loading, setLoading] =
    useState(true);


  // ==========================================================
  // LOAD SYSTEM DATA
  // ==========================================================

  useEffect(() => {

    const initialize = async () => {

      try {

        const health =
          await checkHealth();

        if (health.status === "online") {

          setApiStatus(
            "System Online"
          );

        }


        const dashboardData =
          await getDashboard();

        if (
          dashboardData.success
        ) {

          setDashboard(
            dashboardData
          );

        }

      } catch (error) {

        console.error(
          "Initialization error:",
          error
        );

        setApiStatus(
          "Backend Offline"
        );

      } finally {

        setLoading(false);

      }

    };


    initialize();

  }, []);


  // ==========================================================
  // PAGE TITLE
  // ==========================================================

  const getPageTitle = () => {

    switch (page) {

      case "prediction":
        return "Risk Prediction";

      case "batch":
        return "Batch Analysis";

      case "analytics":
        return "Risk Analytics";

      case "shipments":
        return "Shipment Explorer";

      case "model":
        return "Model Intelligence";

      case "whatif":
        return "What-If Analysis";

      case "history":
        return "Prediction History";

      case "guide":
        return "How It Works";

      default:
        return "Command Center";
    }

  };


  return (

    <div className="app">


      {/* ======================================================
          SIDEBAR
      ====================================================== */}

      <aside
        className={`sidebar ${
          sidebarOpen
            ? "open"
            : "closed"
        }`}
      >

        <div className="brand">

          <div className="brand-icon">

            <Truck size={22} />

          </div>


          {sidebarOpen && (

            <div>

              <div className="brand-name">

                SupplyChain
                <span>IQ</span>

              </div>


              <div className="brand-subtitle">

                Risk Intelligence

              </div>

            </div>

          )}

        </div>


        <nav className="navigation">


          <div className="nav-section">

            {sidebarOpen &&
              "GUIDE"}

          </div>


          <button
            className={`nav-item ${
              page === "guide"
                ? "active"
                : ""
            }`}
            onClick={() =>
              setPage("guide")
            }
          >

            <BookOpen size={19} />

            {sidebarOpen && (
              <span>
                How It Works
              </span>
            )}

          </button>


          <div className="nav-section">

            {sidebarOpen &&
              "COMMAND CENTER"}

          </div>


          <button
            className={`nav-item ${
              page === "dashboard"
                ? "active"
                : ""
            }`}
            onClick={() =>
              setPage("dashboard")
            }
          >

            <LayoutDashboard size={19} />

            {sidebarOpen && (
              <span>
                Command Center
              </span>
            )}

          </button>


          <button
            className={`nav-item ${
              page === "prediction"
                ? "active"
                : ""
            }`}
            onClick={() =>
              setPage("prediction")
            }
          >

            <ShieldAlert size={19} />

            {sidebarOpen && (
              <span>
                Risk Prediction
              </span>
            )}

          </button>


          <button
            className={`nav-item ${
              page === "batch"
                ? "active"
                : ""
            }`}
            onClick={() =>
              setPage("batch")
            }
          >

            <PackageSearch size={19} />

            {sidebarOpen && (
              <span>
                Batch Analysis
              </span>
            )}

          </button>


          <div className="nav-section">

            {sidebarOpen &&
              "INTELLIGENCE"}

          </div>


          <button
            className={`nav-item ${
              page === "analytics"
                ? "active"
                : ""
            }`}
            onClick={() =>
              setPage("analytics")
            }
          >

            <BarChart3 size={19} />

            {sidebarOpen && (
              <span>
                Risk Analytics
              </span>
            )}

          </button>


          <button
            className={`nav-item ${
              page === "shipments"
                ? "active"
                : ""
            }`}
            onClick={() =>
              setPage("shipments")
            }
          >

            <Database size={19} />

            {sidebarOpen && (
              <span>
                Shipment Explorer
              </span>
            )}

          </button>


          <button
            className={`nav-item ${
              page === "model"
                ? "active"
                : ""
            }`}
            onClick={() =>
              setPage("model")
            }
          >

            <BrainCircuit size={19} />

            {sidebarOpen && (
              <span>
                Model Intelligence
              </span>
            )}

          </button>


          <button
            className={`nav-item ${
              page === "whatif"
                ? "active"
                : ""
            }`}
            onClick={() =>
              setPage("whatif")
            }
          >

            <SlidersHorizontal size={19} />

            {sidebarOpen && (
              <span>
                What-If Analysis
              </span>
            )}

          </button>


          <button
            className={`nav-item ${
              page === "history"
                ? "active"
                : ""
            }`}
            onClick={() =>
              setPage("history")
            }
          >

            <History size={19} />

            {sidebarOpen && (
              <span>
                Prediction History
              </span>
            )}

          </button>

        </nav>


        <div className="sidebar-bottom">

          <div className="system-status">

            <span className="status-dot"></span>

            {sidebarOpen && (

              <div>

                <div className="status-title">

                  {apiStatus}

                </div>


                <div className="status-subtitle">

                  AI Engine

                </div>

              </div>

            )}

          </div>

        </div>

      </aside>


      {/* ======================================================
          MAIN
      ====================================================== */}

      <main className="main-content">


        <header className="topbar">

          <button
            className="menu-button"
            onClick={() =>
              setSidebarOpen(
                !sidebarOpen
              )
            }
          >

            {sidebarOpen ? (
              <X size={20} />
            ) : (
              <Menu size={20} />
            )}

          </button>


          <div className="topbar-right">

            <div className="live-indicator">

              <span></span>

              LIVE

            </div>


            <div className="date">

              {getPageTitle()}

            </div>

          </div>

        </header>


        <section className="page-content">

          {loading ? (

            <div className="loading-screen">

              <Activity
                className="spin"
                size={28}
              />

              <span>
                Connecting to SupplyChainIQ...
              </span>

            </div>

          ) : page === "dashboard" ? (

            <Dashboard
              dashboard={dashboard}
            />

          ) : page === "prediction" ? (

            <Prediction />

          ) : page === "analytics" ? (

            <Analytics />

          ) : page === "batch" ? (

            <BatchAnalysis />

          ) : page === "shipments" ? (

            <ShipmentExplorer />

          ) : page === "model" ? (

            <ModelIntelligence />

          ) : page === "whatif" ? (

            <WhatIf />

          ) : page === "history" ? (

            <PredictionHistory />

          ) : page === "guide" ? (

            <Guide />

          ) : (

            <div className="panel coming-soon">

              <BrainCircuit size={38} />

              <h2>
                {getPageTitle()}
              </h2>

              <p>
                This intelligence module is being
                connected to the backend.
              </p>

            </div>

          )}

        </section>


        <footer className="app-footer">

          <span>
            SupplyChainIQ
          </span>

          <span>
            Machine Learning Supply Chain
            Risk Intelligence
          </span>

          <span>
            Prototype
          </span>

        </footer>

      </main>

    </div>

  );
}


export default App;